/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bucket_sort_PDC3 */

#ifndef _Included_bucket_sort_PDC3
#define _Included_bucket_sort_PDC3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bucket_sort_PSort
 * Method:    do_sort
 * Signature: (Ljava/lang/String;[II)[I
 */
JNIEXPORT void JNICALL Java_bucket_1sort_PSort_do_1sort
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
